apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-news-pipeline
  namespace: poc-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-news-pipeline
  template:
    metadata:
      labels:
        app: rag-news-pipeline
    spec:
      containers:
      - name: rag-news-pipeline
        image: kris0022/rag-news-pipeline:latest
        ports:
        - containerPort: 8501