apiVersion: v1
kind: Service
metadata:
  name: rag-news-pipeline-service
spec:
  selector:
    app: rag-news-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer